pages

diff --git a/local b/local
--- a/local
+++ b/local
@@ -21,7 +21,7 @@ if [ "$1" == "component" ] || [ "$1" == "app" ]; then
 fi
 if [ "$1" == "component" ] || [ -z "$1" ]; then
   #How to develop a new component for streamlit from https://github.com/streamlit/component-template
-  #├── build/               <- where py build is generated
+  #├── build/               <- where py build is generated 
   #├── MANIFEST.in          <- change
   #├── setup.py             <- name="X"
   #└── st_tool              <- folder name
@@ -42,5 +42,20 @@ if [ "$1" == "app" ] || [ -z "$1" ]; then
   if [ "$ST_DEV_MODE" == "1" ]; then
     OPTS="-e"
   fi
-  pip install ${OPTS} "./${COMPONENT}" && streamlit run st_app.py
+  APP_FILE=
+  if [ -f ./st_app.py ]; then #Look for st_app.py
+    APP_FILE=st_app.py
+  elif [ -f ./app.py ]; then #Else look for app.py
+    APP_FILE=app.py
+  else
+    APP_FILE=$(eval 'basename "$(realpath $PWD)"').py #Else look for folder name as app name
+    if ! [ -f "$APP_FILE" ]; then
+      APP_FILE=$(eval 'basename "$(realpath $PWD/..)"').py #Else look for parent folder name as app name
+    fi
+    if ! [ -f "$APP_FILE" ]; then
+      echo "*** ERROR *** No app file found - tried st_app.py, app.py, [folder_name].py, [../folder_name].py"
+      exit 1
+    fi
+  fi
+  pip install ${OPTS} "./${COMPONENT}" && streamlit run "$APP_FILE"
 fi
